In [2]:
import torch

In [12]:
x = torch.tensor([1, 2, 3])
y= torch.tensor([8, 9, 10])

#Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

z2 = torch.add(x, y)
print(z2)

z3 = x + y
print(z3)

#Subtraction
z4 = x - y

#Division
torch.true_divide(x, y)

#inplace operations
t = torch.zeros(3)
t.add_(x)

#Exponential
x = x.pow(2)

#Comparison
z = x > 0

#Matrix multiplication
x1 = torch.rand((2, 3))
x2 = torch.rand((3, 6))
x3 = torch.mm(x1, x2)

#Matrix exponential
matrix_exp = torch.rand((4, 4))
print(matrix_exp.matrix_power(3))

#Element wise multiplication
z = x * y

#Batch matrix multiplication
batch = 10
m = 3
n = 4
p = 5

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

#Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2

#Useful tensor opertaions
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)



tensor([ 9., 11., 13.])
tensor([ 9, 11, 13])
tensor([ 9, 11, 13])
tensor([[1.1476, 0.8092, 0.5172, 0.2915],
        [0.9650, 1.3164, 1.3357, 0.3896],
        [0.9899, 1.8883, 2.1026, 0.5141],
        [1.6505, 1.5249, 1.2203, 0.4986]])
