In [1]:
import torch

In [3]:
x = torch.tensor([1, 2, 3])
y= torch.tensor([8, 9, 10])

#Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

z2 = torch.add(x, y)
print(z2)

z3 = x + y
print(z3)

#Subtraction
z4 = x - y

#Division
torch.true_divide(x, y)

#inplace operations
t = torch.zeros(3)
t.add_(x)

#Exponential
x = x.pow(2)

#Comparison
z = x > 0

#Matrix multiplication
x1 = torch.rand((2, 3))
x2 = torch.rand((3, 6))
x3 = torch.mm(x1, x2)

#Matrix exponential
matrix_exp = torch.rand((4, 4))
print(matrix_exp.matrix_power(3))

#Element wise multiplication
z = x * y

#Batch matrix multiplication
batch = 10
m = 3
n = 4
p = 5

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

#Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2

#Useful tensor opertaions
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)

z = torch.clamp(y, min=0, max=10)

x = torch.tensor([1, 0, 1, 1], dtype=torch.bool)
print(torch.any(x))




tensor([ 9., 11., 13.])
tensor([ 9, 11, 13])
tensor([ 9, 11, 13])
tensor([[3.9426, 3.9392, 2.6026, 6.0812],
        [2.6225, 2.7589, 1.6188, 4.1506],
        [3.8521, 3.8911, 2.3424, 5.9098],
        [3.1160, 3.2050, 1.9465, 4.8633]])
tensor(True)


In [14]:
k = torch.rand(3, 5)
rows = torch.tensor([1, 0])
rows

tensor([1, 0])

In [18]:
x = torch.arange(9)
x = x.view(3, 3)
x = x.t()
x

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [21]:
x = torch.rand(2, 5)
y = torch.rand(2, 5)
z = torch.cat((x,y), dim=0)
z

tensor([[0.7849, 0.4670, 0.3673, 0.3868, 0.0835],
        [0.0621, 0.6129, 0.4612, 0.8606, 0.1100],
        [0.1992, 0.1903, 0.6686, 0.7358, 0.3756],
        [0.4082, 0.4759, 0.9712, 0.9182, 0.4781]])